---
# tasks file for createnamespace
- name: Elimina Proyecto OCP
  block:
  - name: Realiza login
    redhat.openshift.openshift_auth:
      username: "{{ openshift_user }}"
      password: "{{ openshift_password }}"
      host: "{{ openshift_api_url }}"
      validate_certs: false
    register: k8s_auth_results
  - name: Elimina Proyecto
    redhat.openshift.k8s:
      api_key: "{{ k8s_auth_results.k8s_auth.api_key }}"
      state: absent
      definition:
        kind: Namespace
      api_version: v1 
      name: "{{ project_name }}"
  always:
  - name: Realiza loguot
    redhat.openshift.openshift_auth:
      state: absent
      api_key: "{{ k8s_auth_results.k8s_auth.api_key }}"
      host: "{{ openshift_api_url }}"
      validate_certs: false
    when: k8s_auth_results.k8s_auth.api_key is defined
